name: Wakatime Stats Charts

on:
  workflow_dispatch:
  schedule:
    # 23:30 KST == 14:30 UTC
    - cron: "30 14 * * *"

jobs:
  update-charts:
    name: Wakatime Stats Charts 업데이트
    runs-on: ubuntu-latest
    steps:
      - uses: Fr4nk1inCs/wakatime-charts@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BRANCH_NAME: waka-weekly  # 브랜치를 여기에서 설정
